modelTypeList = [
    "airplane",
    "fighter-jet",
    "helicopter",
    "space-craft",
    "rocket",
    "space-shuttle",
    "satellite",
    "moon-lander",
    "UFO",
    "hot-air-balloon",
    "drone",
    "glider",
    "bicycle",
    "sports-bike",
    "scooter",
    "motorcycle",
    "ATV",
    "go-kart",
    "race-car",
    "sports-car",
    "supercar",
    "hypercar",
    "classic-car",
    "muscle-car",
    "pickup-truck",
    "monster-truck",
    "SUV",
    "jeep",
    "camper-van",
    "limousine",
    "taxi",
    "police-car",
    "ambulance",
    "fire-truck",
    "school-bus",
    "double-decker-bus",
    "cargo-truck",
    "bulldozer",
    "excavator",
    "crane",
    "tractor",
    "forklift",
    "steam-engine",
    "bullet-train",
    "metro-train",
    "locomotive",
    "tram",
    "yacht",
    "sailboat",
    "speedboat",
    "cruise-ship",
    "pirate-ship",
    "submarine",
    "aircraft-carrier",
    "battleship",
    "lighthouse",
    "castle",
    "medieval-fort",
    "windmill",
    "watermill",
    "log-cabin",
    "treehouse",
    "tiny-house",
    "skyscraper",
    "suspension-bridge",
    "ferris-wheel",
    "roller-coaster",
    "amusement-park",
    "pirate-cannon",
    "treasure-chest",
    "dragon",
    "dinosaur",
    "T-rex",
    "triceratops",
    "elephant",
    "lion",
    "tiger",
    "horse",
    "panda",
    "giant-panda",
    "dolphin",
    "whale",
    "shark",
    "octopus",
    "eagle",
    "owl",
    "peacock",
    "butterfly",
    "spider",
    "robot",
    "humanoid-robot",
    "mech",
    "robot-dog",
    "chess-king",
    "treasure-map",
    "guitar",
    "grand-piano",
    "camera",
    "vintage-clock",
    "globe",
    "telescope",
    "microscope",
    "gaming-controller",
    "game-console",
]

modelTypeList.extend([
    # =========================
    # Airplanes (20)
    # =========================
    "passenger-airliner",
    "cargo-airplane",
    "private-jet",
    "biplane",
    "seaplane",
    "propeller-airplane",
    "stealth-aircraft",
    "supersonic-airliner",
    "flying-wing-aircraft",
    "crop-duster",
    "air-ambulance",
    "water-bomber-aircraft",
    "trainer-aircraft",
    "business-aircraft",
    "vintage-airplane",
    "twin-engine-airplane",
    "single-engine-airplane",
    "delta-wing-aircraft",
    "concept-aircraft",
    "solar-powered-airplane",

    # =========================
    # Jets (20)
    # =========================
    "stealth-fighter-jet",
    "carrier-fighter-jet",
    "interceptor-jet",
    "attack-jet",
    "multirole-fighter",
    "air-superiority-fighter",
    "swept-wing-jet",
    "delta-wing-jet",
    "experimental-jet",
    "supersonic-fighter",
    "trainer-jet",
    "bomber-jet",
    "reconnaissance-jet",
    "VTOL-jet",
    "concept-fighter-jet",
    "canard-fighter-jet",
    "twin-tail-fighter",
    "single-seat-fighter",
    "afterburner-jet",
    "jet-prototype",

    # =========================
    # Space (20)
    # =========================
    "deep-space-probe",
    "space-station",
    "orbital-station",
    "lunar-base",
    "mars-rover",
    "space-observatory",
    "interstellar-spacecraft",
    "orbital-shuttle",
    "space-tug",
    "space-capsule",
    "planetary-lander",
    "orbiter",
    "space-freighter",
    "alien-spacecraft",
    "warp-ship",
    "ring-space-station",
    "space-habitat",
    "exploration-ship",
    "science-vessel",
    "command-spacecraft",

    # =========================
    # Rockets (20)
    # =========================
    "heavy-lift-rocket",
    "reusable-rocket",
    "single-stage-rocket",
    "multi-stage-rocket",
    "moon-mission-rocket",
    "mars-mission-rocket",
    "orbital-launch-vehicle",
    "crew-launch-rocket",
    "cargo-launch-rocket",
    "sounding-rocket",
    "solid-fuel-rocket",
    "liquid-fuel-rocket",
    "deep-space-launcher",
    "rocket-with-boosters",
    "concept-rocket",
    "mini-launch-vehicle",
    "satellite-launch-rocket",
    "exploration-rocket",
    "interplanetary-rocket",
    "rocket-engine-display",

    # =========================
    # Submarines (20)
    # =========================
    "attack-submarine",
    "ballistic-missile-submarine",
    "research-submarine",
    "deep-sea-submersible",
    "mini-submarine",
    "tourist-submarine",
    "exploration-submarine",
    "autonomous-underwater-vehicle",
    "nuclear-submarine",
    "diesel-electric-submarine",
    "rescue-submarine",
    "stealth-submarine",
    "ocean-survey-submarine",
    "underwater-drone",
    "underwater-laboratory",
    "underwater-mining-sub",
    "submarine-with-robotic-arm",
    "deep-ocean-explorer",
    "vintage-submarine",
    "futuristic-submarine",

    # =========================
    # Boats (20)
    # =========================
    "fishing-boat",
    "lifeboat",
    "canoe",
    "kayak",
    "catamaran",
    "trimaran",
    "river-boat",
    "houseboat",
    "patrol-boat",
    "naval-destroyer",
    "frigate",
    "container-ship",
    "oil-tanker",
    "icebreaker-ship",
    "hovercraft",
    "rescue-boat",
    "pontoon-boat",
    "rowing-boat",
    "luxury-yacht",
    "speed-racing-boat",

    # =========================
    # Dragons (20)
    # =========================
    "eastern-dragon",
    "western-dragon",
    "ice-dragon",
    "fire-dragon",
    "forest-dragon",
    "storm-dragon",
    "crystal-dragon",
    "mechanical-dragon",
    "sea-dragon",
    "sky-dragon",
    "golden-dragon",
    "shadow-dragon",
    "two-headed-dragon",
    "three-headed-dragon",
    "wingless-dragon",
    "baby-dragon",
    "elder-dragon",
    "armored-dragon",
    "lava-dragon",
    "serpent-dragon",

    # =========================
    # Robots (20)
    # =========================
    "service-robot",
    "industrial-robot",
    "medical-robot",
    "battle-robot",
    "companion-robot",
    "android",
    "cyborg",
    "quadruped-robot",
    "robot-spider",
    "robot-scorpion",
    "construction-robot",
    "warehouse-robot",
    "flying-robot",
    "rescue-robot",
    "space-robot",
    "exploration-robot",
    "robot-butler",
    "giant-mech",
    "transformer-style-robot",
    "AI-assistant-robot",

    # =========================
    # Spiders (20)
    # =========================
    "jumping-spider",
    "wolf-spider",
    "orb-weaver-spider",
    "tarantula",
    "black-widow-spider",
    "golden-orb-spider",
    "crab-spider",
    "trapdoor-spider",
    "camel-spider",
    "huntsman-spider",
    "garden-spider",
    "spiny-spider",
    "peacock-spider",
    "giant-spider",
    "fantasy-spider",
    "mechanical-spider",
    "armored-spider",
    "crystal-spider",
    "ice-spider",
    "fire-spider",

    # =========================
    # Dogs (20)
    # =========================
    "golden-retriever",
    "labrador",
    "german-shepherd",
    "husky",
    "doberman",
    "rottweiler",
    "beagle",
    "pug",
    "corgi",
    "border-collie",
    "dalmatian",
    "shiba-inu",
    "akita",
    "saint-bernard",
    "great-dane",
    "boxer-dog",
    "bulldog",
    "chihuahua",
    "poodle",
    "greyhound",

    # =========================
    # Microscopes (20)
    # =========================
    "compound-microscope",
    "digital-microscope",
    "electron-microscope",
    "stereo-microscope",
    "fluorescence-microscope",
    "confocal-microscope",
    "USB-microscope",
    "laboratory-microscope",
    "portable-microscope",
    "research-microscope",
    "phase-contrast-microscope",
    "polarizing-microscope",
    "metallurgical-microscope",
    "biological-microscope",
    "educational-microscope",
    "trinocular-microscope",
    "inverted-microscope",
    "vintage-microscope",
    "futuristic-microscope",
    "AI-microscope",

    # =========================
    # Telescopes (20)
    # =========================
    "refractor-telescope",
    "reflector-telescope",
    "dobsonian-telescope",
    "catadioptric-telescope",
    "radio-telescope",
    "solar-telescope",
    "space-telescope",
    "observatory-telescope",
    "portable-telescope",
    "computerized-telescope",
    "equatorial-telescope",
    "altazimuth-telescope",
    "deep-space-telescope",
    "planetary-telescope",
    "astrophotography-telescope",
    "finder-scope",
    "binocular-telescope",
    "vintage-telescope",
    "futuristic-telescope",
    "professional-observatory-telescope",
])


categoryVariants = {
    "gun": [
        "revolver",
        "semi-automatic-pistol",
        "desert-pistol",
        "compact-pistol",
        "machine-pistol",
        "assault-rifle",
        "battle-rifle",
        "bullpup-rifle",
        "lever-action-rifle",
        "bolt-action-rifle",
        "submachine-gun",
        "shotgun",
        "double-barrel-shotgun",
        "pump-action-shotgun",
        "light-machine-gun",
        "heavy-machine-gun",
        "anti-material-rifle",
        "sci-fi-blaster",
        "steampunk-rifle",
        "vintage-musket",
    ],

    "bow-arrow": [
        "longbow",
        "recurve-bow",
        "compound-bow",
        "crossbow",
        "traditional-bow",
        "hunting-bow",
        "target-bow",
        "samurai-yumi",
        "elven-bow",
        "fantasy-bow",
        "fire-arrow",
        "ice-arrow",
        "double-arrow",
        "quiver-and-arrow",
        "golden-arrow",
    ],

    "sports-car": [
        "hypercar",
        "supercar",
        "concept-supercar",
        "track-car",
        "GT-race-car",
        "drift-car",
        "formula-race-car",
        "electric-supercar",
        "classic-sports-car",
        "convertible-sports-car",
        "widebody-supercar",
        "carbon-fiber-supercar",
        "luxury-coupe",
        "future-concept-car",
        "street-racer",
        "muscle-sports-car",
    ],

    "DJ": [
        "dj-turntable",
        "dj-mixer",
        "dual-turntable",
        "dj-controller",
        "vinyl-record",
        "headphones",
        "club-dj-booth",
        "festival-dj-stage",
        "neon-dj-console",
        "vinyl-player",
        "dj-equalizer",
        "dj-headset",
        "music-waveform",
        "audio-fader",
        "nightclub-console",
    ],

    "speakers": [
        "bookshelf-speaker",
        "tower-speaker",
        "studio-monitor",
        "subwoofer",
        "bluetooth-speaker",
        "portable-speaker",
        "party-speaker",
        "smart-speaker",
        "car-speaker",
        "dual-speaker-stack",
        "concert-speaker",
        "speaker-array",
        "woofer-and-tweeter",
        "bass-box",
        "retro-speaker",
    ],

    "spider-web": [
        "circular-web",
        "corner-web",
        "dew-covered-web",
        "broken-web",
        "symmetrical-web",
        "spiral-web",
        "hanging-web",
        "giant-web",
        "fantasy-web",
        "gothic-web",
        "web-with-spider",
        "minimal-web",
    ],

    "bat": [
        "baseball-bat",
        "cricket-bat",
        "wooden-bat",
        "metal-bat",
        "spiked-bat",
        "barbed-wire-bat",
        "combat-bat",
        "vampire-bat",
        "flying-bat",
        "bat-silhouette",
        "tribal-bat",
        "bat-with-wings",
    ],

    "marvel-logos": [
        "shield-logo",
        "hammer-logo",
        "arc-reactor",
        "mask-logo",
        "spider-emblem",
        "star-emblem",
        "panther-head",
        "captain-shield",
        "gauntlet",
        "hex-symbol",
        "eye-symbol",
        "wakanda-symbol",
    ],

    "crocodile": [
        "saltwater-crocodile",
        "freshwater-crocodile",
        "baby-crocodile",
        "open-mouth-crocodile",
        "swimming-crocodile",
        "armored-crocodile",
        "tribal-crocodile",
        "mechanical-crocodile",
        "fantasy-crocodile",
        "ancient-crocodile",
    ],

    "sniper": [
        "bolt-action-sniper",
        "modern-sniper",
        "camouflaged-sniper",
        "suppressed-sniper",
        "long-range-sniper",
        "military-sniper",
        "urban-sniper",
        "thermal-sniper",
        "futuristic-sniper",
        "precision-rifle",
    ],

    "tank": [
        "battle-tank",
        "heavy-tank",
        "light-tank",
        "modern-tank",
        "WW2-tank",
        "desert-tank",
        "urban-tank",
        "camouflage-tank",
        "hover-tank",
        "futuristic-tank",
        "railgun-tank",
        "missile-tank",
    ],

    "missile": [
        "ballistic-missile",
        "cruise-missile",
        "air-to-air-missile",
        "air-to-ground-missile",
        "surface-to-air-missile",
        "hypersonic-missile",
        "rocket-missile",
        "guided-missile",
        "interceptor-missile",
        "space-missile",
    ],

    "bullet-train": [
        "japanese-bullet-train",
        "high-speed-train",
        "maglev-train",
        "streamlined-train",
        "futuristic-bullet-train",
        "double-decker-high-speed-train",
        "european-high-speed-train",
        "metro-express",
        "concept-bullet-train",
        "sleek-train",
    ],

    "cat": [
        "persian-cat",
        "maine-coon",
        "siamese-cat",
        "bengal-cat",
        "british-shorthair",
        "black-cat",
        "white-cat",
        "orange-tabby",
        "kitten",
        "sleeping-cat",
        "jumping-cat",
        "tribal-cat",
    ],

    "grenade": [
        "fragmentation-grenade",
        "smoke-grenade",
        "flash-grenade",
        "incendiary-grenade",
        "classic-pineapple-grenade",
        "modern-grenade",
        "tactical-grenade",
        "futuristic-grenade",
        "EMP-grenade",
        "mini-grenade",
    ],

    "katana": [
        "samurai-katana",
        "dual-katanas",
        "curved-katana",
        "ornamental-katana",
        "battle-katana",
        "ancient-katana",
        "damascus-katana",
        "ninja-katana",
        "sheathed-katana",
        "crossed-katanas",
    ],

    "tactical-shield": [
        "riot-shield",
        "ballistic-shield",
        "transparent-shield",
        "combat-shield",
        "spartan-shield",
        "energy-shield",
        "hexagonal-shield",
        "futuristic-shield",
        "reinforced-shield",
        "police-shield",
    ],

    "brass-knuckles": [
        "classic-brass-knuckles",
        "spiked-knuckles",
        "skull-knuckles",
        "engraved-knuckles",
        "heavy-knuckles",
        "minimal-knuckles",
        "tactical-knuckles",
        "carbon-knuckles",
        "mechanical-knuckles",
        "tribal-knuckles",
    ],

    "cobra-viper": [
        "king-cobra",
        "spectacled-cobra",
        "black-mamba",
        "green-viper",
        "pit-viper",
        "coiled-cobra",
        "hooded-cobra",
        "striking-viper",
        "tribal-cobra",
        "mechanical-cobra",
    ],

    "black-panther": [
        "panther-head",
        "panther-face",
        "roaring-panther",
        "running-panther",
        "jumping-panther",
        "tribal-panther",
        "cyber-panther",
        "minimal-panther",
        "panther-claws",
        "panther-eyes",
    ],

    "great-white-shark": [
        "great-white-head",
        "open-mouth-shark",
        "breaching-shark",
        "shark-profile",
        "tribal-shark",
        "mechanical-shark",
        "cyber-shark",
        "ocean-shark",
        "deep-sea-shark",
        "shark-fin",
    ],

    "shark-tooth": [
        "single-shark-tooth",
        "fossil-tooth",
        "serrated-tooth",
        "necklace-tooth",
        "tribal-tooth",
        "double-tooth",
        "crossed-teeth",
        "ancient-tooth",
        "stylized-tooth",
        "minimal-tooth",
    ],

    "scorpion": [
        "desert-scorpion",
        "emperor-scorpion",
        "black-scorpion",
        "tribal-scorpion",
        "mechanical-scorpion",
        "armored-scorpion",
        "glowing-scorpion",
        "fantasy-scorpion",
        "minimal-scorpion",
        "coiled-scorpion",
    ],

    "cybernetic-eye": [
        "robotic-eye",
        "AI-eye",
        "scanning-eye",
        "targeting-eye",
        "glitch-eye",
        "holographic-eye",
        "mechanical-iris",
        "digital-eye",
        "cyber-visor",
        "optic-lens",
    ],

    "chained-skull": [
        "skull-with-chain",
        "burning-skull",
        "mechanical-skull",
        "cracked-skull",
        "hooded-skull",
        "tribal-skull",
        "minimal-skull",
        "double-skull",
        "winged-skull",
        "crowned-skull",
    ],

    "lightning-bolt": [
        "single-bolt",
        "double-bolt",
        "electric-arc",
        "storm-bolt",
        "zigzag-bolt",
        "energy-bolt",
        "plasma-bolt",
        "tribal-lightning",
        "minimal-lightning",
        "glowing-lightning",
    ],

    "ace-of-spades": [
        "classic-ace-of-spades",
        "ornamental-spade",
        "skull-spade",
        "flaming-spade",
        "tribal-spade",
        "minimal-spade",
        "royal-spade",
        "engraved-spade",
        "dark-spade",
        "playing-card-spade",
    ],

    "spartan-helmet": [
        "classic-spartan-helmet",
        "battle-worn-helmet",
        "winged-helmet",
        "roman-spartan-style",
        "golden-helmet",
        "minimal-helmet",
        "tribal-helmet",
        "warrior-helmet",
        "ancient-helmet",
        "gladiator-helmet",
    ],

    "biohazard-sign": [
        "classic-biohazard",
        "minimal-biohazard",
        "glowing-biohazard",
        "industrial-biohazard",
        "warning-biohazard",
        "distressed-biohazard",
        "cyber-biohazard",
        "hazmat-symbol",
        "infected-symbol",
        "mutated-symbol",
    ],

    "radiation": [
        "classic-radiation-symbol",
        "minimal-radiation",
        "hazard-radiation",
        "nuclear-warning",
        "glowing-radiation",
        "industrial-radiation",
        "weathered-radiation",
        "cyber-radiation",
        "radioactive-core",
        "trefoil-emblem",
    ],

    "cybernetic-glitch": [
        "barcode",
        "broken-barcode",
        "glitch-lines",
        "QR-pattern",
        "binary-code",
        "digital-noise",
        "pixel-glitch",
        "scan-lines",
        "AI-circuit",
        "cyber-grid",
    ],

    "broken-chain-link": [
        "single-broken-chain",
        "snapped-chain",
        "heavy-chain",
        "rusted-chain",
        "crossed-chain",
        "wrapped-chain",
        "tribal-chain",
        "steel-chain",
        "minimal-chain",
        "floating-chain",
    ],

    "heart": [
        "classic-heart",
        "anatomical-heart",
        "broken-heart",
        "flaming-heart",
        "mechanical-heart",
        "cyber-heart",
        "winged-heart",
        "sacred-heart",
        "heartbeat-line",
        "minimal-heart",
        "geometric-heart",
        "pixel-heart",
        "tribal-heart",
        "crystal-heart",
        "lock-and-key-heart",
    ],
}





modelTypeList = [
    item
    for categoryList in categoryVariants.values()
    for item in categoryList
]


tempPrompt = """
Create a high-quality @@@modelType@@@ miniature crafted entirely from thin white cardboard, with no colors, textures, prints, or markings. The model should have a clean pop-traditional papercraft style with precise folds, crisp edges, and realistic proportions, viewed from the front angle to clearly showcase its shape and details. Place it neatly on a plain white desk against a pure white seamless background, creating a clean studio setup with soft, even lighting, subtle natural shadows, sharp focus, and a premium handcrafted appearance that keeps the entire focus on the white cardboard model.
"""
lenModelTypeList = len(modelTypeList)

try:
    with open("pop-prompt-v2.txt", "w", encoding="utf-8") as file:
        for idx, item in enumerate(modelTypeList):
            prompt = tempPrompt.replace("@@@modelType@@@", item)

            # print(f"{idx + 1}/{lenModelTypeList} : {prompt}")

            file.write(f"{idx + 1}/{lenModelTypeList} : {prompt}")
            file.write("\n\n")

    print(f"\nSuccessfully saved {lenModelTypeList} prompts to 'pop-prompt.txt'.")

except Exception as err:
    print(f"Error while saving prompts: {err}")