# Generated by Django 4.0.6 on 2025-06-28 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('emailid', models.TextField()),
                ('msg', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternDetails',
            fields=[
                ('internid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='*')),
                ('role', models.TextField(default='*')),
                ('experience', models.TextField(default='*')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('photo_base64', models.TextField(default='*')),
                ('metadata', models.TextField(default='*')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('prodid', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.TextField(default='*')),
                ('productcat', models.TextField(default='*')),
                ('mainimgbasetxt', models.TextField(default='*')),
                ('highlighttitle', models.TextField(default='*')),
                ('prodinfo', models.TextField(default='*')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('devid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='*')),
                ('role', models.TextField(default='*')),
                ('experience', models.TextField(default='*')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('photo_base64', models.TextField(default='*')),
                ('metadata', models.TextField(default='*')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YTvideos',
            fields=[
                ('ytid', models.AutoField(primary_key=True, serialize=False)),
                ('videotitle', models.TextField(default='*')),
                ('videolink', models.TextField(default='*')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFavProjects',
            fields=[
                ('favid', models.AutoField(primary_key=True, serialize=False)),
                ('metadata', models.TextField(default='*')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.productinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fav', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('myuid', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField(default='*')),
                ('contactno', models.TextField(default='*')),
                ('refid', models.TextField(default='*')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductYT',
            fields=[
                ('pimgid', models.AutoField(primary_key=True, serialize=False)),
                ('yttitle', models.TextField(default='*')),
                ('ytlink', models.TextField(default='*')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.productinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImgs',
            fields=[
                ('pimgid', models.AutoField(primary_key=True, serialize=False)),
                ('highlighttitle', models.TextField(default='*')),
                ('mainimgbasetxt', models.TextField(default='*')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.productinfo')),
            ],
        ),
    ]
