# Generated by Django 4.0.6 on 2025-07-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeimgs',
            fields=[
                ('hiid', models.AutoField(primary_key=True, serialize=False)),
                ('imgtitle', models.TextField(default='*')),
                ('imglink', models.TextField(default='*')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='interndetails',
            name='applicationlink',
            field=models.TextField(default='*'),
        ),
        migrations.AddField(
            model_name='interndetails',
            name='certificatelink',
            field=models.TextField(default='*'),
        ),
    ]
