# Generated by Django 4.0.6 on 2025-07-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_homeimgs_interndetails_applicationlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='prodtags',
            field=models.TextField(default='*'),
        ),
    ]
