# Generated by Django 4.0.6 on 2025-07-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_productinfo_prodtags'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarnTask',
            fields=[
                ('etid', models.AutoField(primary_key=True, serialize=False)),
                ('etitle', models.TextField(default='*')),
                ('eamount', models.TextField(default='*')),
                ('edescribe', models.TextField(default='*')),
                ('estatus', models.TextField(default='active')),
                ('eimglink', models.TextField(default='*')),
                ('eseatscap', models.TextField(default='*')),
                ('emetadata', models.TextField(default='*')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
