# Generated by Django 5.0.3 on 2025-12-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_earntask'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoriesProd',
            fields=[
                ('apid', models.AutoField(primary_key=True, serialize=False)),
                ('aptitle', models.TextField(default='*')),
                ('apheader', models.TextField(default='*')),
                ('apdesc', models.TextField(default='*')),
                ('apprice', models.TextField(default='*')),
                ('apsale', models.TextField(default='*')),
                ('apimglink', models.TextField(default='*')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
