# Generated by Django 5.0.3 on 2025-12-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_accessoriesprod'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriesprod',
            name='aptag',
            field=models.TextField(default='*'),
        ),
    ]
