# Generated by Django 5.0.3 on 2026-01-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_accessoriesprod_aptag'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='prodcost',
            field=models.TextField(default='*'),
        ),
    ]
