# Generated by Django 5.0.3 on 2026-01-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_productinfo_prodcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='AicontentProd',
            fields=[
                ('aiid', models.AutoField(primary_key=True, serialize=False)),
                ('aititle', models.TextField(default='*')),
                ('aiheader', models.TextField(default='*')),
                ('aidesc', models.TextField(default='*')),
                ('aiprice', models.TextField(default='*')),
                ('aisale', models.TextField(default='*')),
                ('aiimglink', models.TextField(default='*')),
                ('aitag', models.TextField(default='*')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
