# Generated by Django 5.0.3 on 2026-01-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_aicontentprod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productyt',
            name='prod',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='gallery',
            field=models.TextField(default='*'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='ytlinks',
            field=models.TextField(default='*'),
        ),
        migrations.DeleteModel(
            name='ProductImgs',
        ),
        migrations.DeleteModel(
            name='ProductYT',
        ),
    ]
