# Generated by Django 5.0.3 on 2026-01-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_productyt_prod_productinfo_gallery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Businesswebinfo',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('bname', models.TextField(default='*')),
                ('bcat', models.TextField(default='*')),
                ('bmainimg', models.TextField(default='*')),
                ('btags', models.TextField(default='*')),
                ('bhighlight', models.TextField(default='*')),
                ('binfo', models.TextField(default='*')),
                ('bownerimgs', models.TextField(default='*')),
                ('bgallery', models.TextField(default='*')),
                ('bytlinks', models.TextField(default='*')),
                ('bweblinks', models.TextField(default='*')),
                ('btimestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
