# Generated by Django 5.0.3 on 2026-07-15 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_interndetails_is_stipend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavprojects',
            name='prod',
        ),
        migrations.RemoveField(
            model_name='userfavprojects',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
        migrations.DeleteModel(
            name='UserFavProjects',
        ),
    ]
