# Generated by Django 5.0.3 on 2026-07-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_remove_userfavprojects_prod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternOpportunity',
            fields=[
                ('opid', models.PositiveIntegerField(help_text='Stable catalog ID from intern-ops.txt.', primary_key=True, serialize=False)),
                ('title', models.TextField(default='*')),
                ('track', models.TextField(default='*')),
                ('mode', models.TextField(default='*')),
                ('duration', models.TextField(default='*')),
                ('stipend', models.TextField(default='*')),
                ('is_stipend', models.BooleanField(default=False, help_text='Toggle ON for stipend (paid); OFF for unstipend (unpaid).')),
                ('skills', models.TextField(default='*')),
                ('description', models.TextField(default='*')),
                ('is_visible', models.BooleanField(default=True, help_text='If unchecked, hidden from the public list. In intern-ops.txt: | = visible, - = hide.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'intern opportunities',
                'ordering': ['opid'],
            },
        ),
    ]
