# Generated by Django 5.0.3 on 2026-07-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_internopportunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeimgs',
            name='imglink',
            field=models.TextField(default='*', help_text='Image URL. Empty or "*" is treated as missing and excluded from public pages.'),
        ),
        migrations.AlterField(
            model_name='homeimgs',
            name='imgtitle',
            field=models.TextField(default='*', help_text='Public visibility: set a real title to show on hero/gallery. Empty or "*" hides the image.'),
        ),
    ]
