# Generated by Django 5.0.3 on 2026-07-16 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_homeimgs_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('catid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name, e.g. Software', max_length=64, unique=True)),
                ('slug', models.SlugField(help_text='URL key, e.g. software (used as ?productcat=software)', max_length=64, unique=True)),
                ('legacy_slugs', models.TextField(blank=True, default='', help_text='Comma-separated old productcat values (e.g. softwareprojects,kidsscience).')),
                ('hashtags', models.TextField(blank=True, default='', help_text='Comma-separated sub-category hashtags shown as quick filters.')),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'product categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='productcat',
            field=models.TextField(default='*', help_text='Legacy text category. Prefer linking ProductCategory via the category field.'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Structured category (Software, Hardware, Mechanical, Simulation, Science, Craft).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='mainapp.productcategory'),
        ),
    ]
