# Generated by Django 5.0.3 on 2026-07-16 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CraftProduct',
            fields=[
                ('prodid', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.TextField(default='*')),
                ('mainimgbasetxt', models.TextField(default='*')),
                ('prodtags', models.TextField(default='*')),
                ('prodcost', models.TextField(default='*')),
                ('highlighttitle', models.TextField(default='*')),
                ('prodinfo', models.TextField(default='*')),
                ('gallery', models.TextField(default='*')),
                ('ytlinks', models.TextField(default='*')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Craft project',
                'verbose_name_plural': 'Craft projects',
                'ordering': ['-timestamp'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HardwareProduct',
            fields=[
                ('prodid', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.TextField(default='*')),
                ('mainimgbasetxt', models.TextField(default='*')),
                ('prodtags', models.TextField(default='*')),
                ('prodcost', models.TextField(default='*')),
                ('highlighttitle', models.TextField(default='*')),
                ('prodinfo', models.TextField(default='*')),
                ('gallery', models.TextField(default='*')),
                ('ytlinks', models.TextField(default='*')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hardware project',
                'verbose_name_plural': 'Hardware projects',
                'ordering': ['-timestamp'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MechanicalProduct',
            fields=[
                ('prodid', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.TextField(default='*')),
                ('mainimgbasetxt', models.TextField(default='*')),
                ('prodtags', models.TextField(default='*')),
                ('prodcost', models.TextField(default='*')),
                ('highlighttitle', models.TextField(default='*')),
                ('prodinfo', models.TextField(default='*')),
                ('gallery', models.TextField(default='*')),
                ('ytlinks', models.TextField(default='*')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mechanical project',
                'verbose_name_plural': 'Mechanical projects',
                'ordering': ['-timestamp'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScienceProduct',
            fields=[
                ('prodid', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.TextField(default='*')),
                ('mainimgbasetxt', models.TextField(default='*')),
                ('prodtags', models.TextField(default='*')),
                ('prodcost', models.TextField(default='*')),
                ('highlighttitle', models.TextField(default='*')),
                ('prodinfo', models.TextField(default='*')),
                ('gallery', models.TextField(default='*')),
                ('ytlinks', models.TextField(default='*')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Science project',
                'verbose_name_plural': 'Science projects',
                'ordering': ['-timestamp'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimulationProduct',
            fields=[
                ('prodid', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.TextField(default='*')),
                ('mainimgbasetxt', models.TextField(default='*')),
                ('prodtags', models.TextField(default='*')),
                ('prodcost', models.TextField(default='*')),
                ('highlighttitle', models.TextField(default='*')),
                ('prodinfo', models.TextField(default='*')),
                ('gallery', models.TextField(default='*')),
                ('ytlinks', models.TextField(default='*')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Simulation project',
                'verbose_name_plural': 'Simulation projects',
                'ordering': ['-timestamp'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoftwareProduct',
            fields=[
                ('prodid', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.TextField(default='*')),
                ('mainimgbasetxt', models.TextField(default='*')),
                ('prodtags', models.TextField(default='*')),
                ('prodcost', models.TextField(default='*')),
                ('highlighttitle', models.TextField(default='*')),
                ('prodinfo', models.TextField(default='*')),
                ('gallery', models.TextField(default='*')),
                ('ytlinks', models.TextField(default='*')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Software project',
                'verbose_name_plural': 'Software projects',
                'ordering': ['-timestamp'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Legacy FK — prefer per-category product models.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='mainapp.productcategory'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='productcat',
            field=models.TextField(default='*'),
        ),
    ]
