# Generated by Django 5.0.3 on 2026-07-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_rename_project_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='documents',
            field=models.TextField(default='*', help_text='Semicolon-separated document URLs (ppt, pdf, doc, …). Optional label: Label|https://example.com/file.pdf'),
        ),
        migrations.AddField(
            model_name='project_craft',
            name='documents',
            field=models.TextField(default='*', help_text='Semicolon-separated document URLs (ppt, pptx, pdf, doc, docx, xls, xlsx, …). Optional label: Label|https://example.com/file.pdf'),
        ),
        migrations.AddField(
            model_name='project_hardware',
            name='documents',
            field=models.TextField(default='*', help_text='Semicolon-separated document URLs (ppt, pptx, pdf, doc, docx, xls, xlsx, …). Optional label: Label|https://example.com/file.pdf'),
        ),
        migrations.AddField(
            model_name='project_mechanical',
            name='documents',
            field=models.TextField(default='*', help_text='Semicolon-separated document URLs (ppt, pptx, pdf, doc, docx, xls, xlsx, …). Optional label: Label|https://example.com/file.pdf'),
        ),
        migrations.AddField(
            model_name='project_science',
            name='documents',
            field=models.TextField(default='*', help_text='Semicolon-separated document URLs (ppt, pptx, pdf, doc, docx, xls, xlsx, …). Optional label: Label|https://example.com/file.pdf'),
        ),
        migrations.AddField(
            model_name='project_simulation',
            name='documents',
            field=models.TextField(default='*', help_text='Semicolon-separated document URLs (ppt, pptx, pdf, doc, docx, xls, xlsx, …). Optional label: Label|https://example.com/file.pdf'),
        ),
        migrations.AddField(
            model_name='project_software',
            name='documents',
            field=models.TextField(default='*', help_text='Semicolon-separated document URLs (ppt, pptx, pdf, doc, docx, xls, xlsx, …). Optional label: Label|https://example.com/file.pdf'),
        ),
    ]
