# Generated by Django 5.0.3 on 2026-07-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_product_documents_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='components',
            field=models.TextField(default='*', help_text='Semicolon-separated component image URLs (optional Label|URL).'),
        ),
        migrations.AddField(
            model_name='project_craft',
            name='components',
            field=models.TextField(default='*', help_text='Semicolon-separated component image URLs. Optional label: Label|https://example.com/part.jpg'),
        ),
        migrations.AddField(
            model_name='project_hardware',
            name='components',
            field=models.TextField(default='*', help_text='Semicolon-separated component image URLs. Optional label: Label|https://example.com/part.jpg'),
        ),
        migrations.AddField(
            model_name='project_mechanical',
            name='components',
            field=models.TextField(default='*', help_text='Semicolon-separated component image URLs. Optional label: Label|https://example.com/part.jpg'),
        ),
        migrations.AddField(
            model_name='project_science',
            name='components',
            field=models.TextField(default='*', help_text='Semicolon-separated component image URLs. Optional label: Label|https://example.com/part.jpg'),
        ),
        migrations.AddField(
            model_name='project_simulation',
            name='components',
            field=models.TextField(default='*', help_text='Semicolon-separated component image URLs. Optional label: Label|https://example.com/part.jpg'),
        ),
        migrations.AddField(
            model_name='project_software',
            name='components',
            field=models.TextField(default='*', help_text='Semicolon-separated component image URLs. Optional label: Label|https://example.com/part.jpg'),
        ),
    ]
