"""
Django settings for handmadeprojects project.

Originally generated by 'django-admin startproject' using Django 4.0.6;
the project now runs on Django 5.0.3 (see requirements.txt).

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import sys
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


def _patch_composite_primary_key_for_libsql():
    """django-libsql-backend 0.1.x imports CompositePrimaryKey (Django 5.2+)."""
    from django.db import models as django_models

    if not hasattr(django_models, "CompositePrimaryKey"):
        class CompositePrimaryKey:
            pass

        django_models.CompositePrimaryKey = CompositePrimaryKey


_patch_composite_primary_key_for_libsql()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-63&#nb_&6i(a(q1!t3tl=y+z-ts+07c$+pd+u($@&wovepn!)q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

# ALLOWED_HOSTS = ['handmadeprojects.pythonanywhere.com']

RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")

ALLOWED_HOSTS = ['*', "localhost", "127.0.0.1", 'mydjtest.onrender.com']

if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# No public-facing login/register flow — the only login page is the Django
# admin's, used solely by the site owner to manage content.
LOGIN_URL = '/hpmadmin/login/'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'mainapp',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'handmadeprojects.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'mainapp.context_processors.contact_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'handmadeprojects.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
#
# Default: Turso (libSQL) when TURSO_DATABASE_URL + TURSO_AUTH_TOKEN are set.
# Fallback: local db.sqlite3. Tests always use Django's sqlite3 backend so they
# never create/destroy a database on the cloud.

def _to_http_database_url(database_url: str) -> str:
    """AWS Turso does not support WebSockets; libsql:// must be https://."""
    if database_url.startswith("libsql://"):
        return "https://" + database_url[len("libsql://"):]
    if database_url.startswith("wss://"):
        return "https://" + database_url[len("wss://"):]
    return database_url


def _is_running_tests() -> bool:
    settings_module = os.environ.get("DJANGO_SETTINGS_MODULE", "")
    if settings_module.endswith("settings_test"):
        return True
    return len(sys.argv) >= 2 and sys.argv[1] == "test"


def _use_turso() -> bool:
    if _is_running_tests():
        return False
    flag = os.environ.get("USE_TURSO", "1").strip().lower()
    if flag in {"0", "false", "no", "off"}:
        return False
    return bool(
        os.environ.get("TURSO_DATABASE_URL", "").strip()
        and os.environ.get("TURSO_AUTH_TOKEN", "").strip()
    )


def _build_default_database() -> dict:
    if _use_turso():
        return {
            "ENGINE": "django_libsql",
            "NAME": _to_http_database_url(os.environ["TURSO_DATABASE_URL"].strip()),
            "AUTH_TOKEN": os.environ["TURSO_AUTH_TOKEN"].strip(),
            "OPTIONS": {"timeout": 30},
        }
    return dj_database_url.config(default="sqlite:///db.sqlite3")


DATABASES = {
    "default": _build_default_database(),
}



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Kolkata'


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# default static files settings for PythonAnywhere.
# see https://help.pythonanywhere.com/pages/DjangoStaticFiles for more info
# MEDIA_ROOT = '/home/handmadeprojects/media'
# MEDIA_URL = '/media/'
# STATIC_ROOT = '/home/handmadeprojects/handmadeprojects/static'
# STATIC_URL = '/static/'



# Single source of truth for site contact numbers — used by
# mainapp.context_processors.contact_info so templates never hardcode them.
CONTACT_PHONE_DISPLAY = '+91 81692 39027'
CONTACT_PHONE_TEL = '+918169239027'
CONTACT_WHATSAPP_NUMBER = '918169239027'

# Alternate contact number
CONTACT_PHONE_ALT_DISPLAY = '+91 93206 68111'
CONTACT_PHONE_ALT_TEL = '+919320668111'
CONTACT_WHATSAPP_ALT_NUMBER = '919320668111'

CONTACT_WHATSAPP_DEFAULT_MESSAGE = 'Hi HandMadeProjects, I have a query.'


STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    BASE_DIR / 'mainapp' / 'static',
]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
